name: "AppImage creator"
description: "Used to generate AppImage packages"
author: "Emiliopg91"
branding:
  icon: activity
  color: white
inputs:
  is_electron:
    description: "Apply Electron rules"
    required: false
    default: "false"
outputs:
  version:
    description: "Application version"
  is_update:
    description: "Decision if the AppImage needs to be updated"
  appimage_path:
    description: "Full-path to appimage"
runs:
  using: "composite"
  steps:
    - run: echo "INPUT_IS_ELECTRON=${{ inputs.is_electron }}" >> $GITHUB_ENV
      shell: bash
    - run: sudo apt-get update
      shell: bash
    - run: sudo apt-get install -y jq libfuse2 zsync
      shell: bash
    - run: pip install --upgrade certifi
      shell: bash
    - run: chmod +x $GITHUB_ACTION_PATH/resources/appimagetool
      shell: bash
    - run: |
        if [[ "${{ inputs.is_electron }}" == "true" ]]; then
          python3 -u $GITHUB_ACTION_PATH/createElectronAppImage.py
        else
          python3 -u $GITHUB_ACTION_PATH/createAppImage.py
        fi
      shell: bash
