name: "AppImage creator"
description: "Used to generate AppImage packages"
author: "Emiliopg91"
branding:
  icon: activity
  color: white
outputs:
  version:
    description: "Application version"
  is_update:
    description: "Decision if the AppImage needs to be updated"
  appimage_path:
    description: "Full-path to appimage"
runs:
  using: "composite"
  steps:
    - run: sudo apt-get update
      shell: bash
    - run: sudo apt-get install -y jq libfuse2 desktop-file-utils fuse zsync
      shell: bash
    - run: pip install --upgrade certifi
      shell: bash
    - run: python3 -u $GITHUB_ACTION_PATH/createAppImage.py
      shell: bash
